services:
  db:
    image: postgres:16-alpine
    container_name: it-guru_postgres
    environment:
      POSTGRES_DB: it-guru
      POSTGRES_USER: it-guru
      POSTGRES_PASSWORD: it-guru
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U it-guru -d it-guru"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: it-guru_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
